version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=lofty
      - POSTGRES_USER=cjem
      - POSTGRES_PASSWORD=hellolego
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=lofty
      - POSTGRES_USER=cjem
      - POSTGRES_PASSWORD=hellolego
    depends_on:
      - db
